tmp_dir: gen_rfl
src_dir: ./
libs_dir: libs
include_dir: include
source_pattern: .+\.(cpp|c++|cc|cxx|h|hpp|hxx)$
cmake_pattern: ^.*/CMakeFiles/.+/CMake.+$
llvm_args:
  - --std=c++20
  - -I/usr/include
  - -I/usr/include/c++/12
  - -I/usr/include/x86_64-linux-gnu/c++/12
  - -I/usr/lib/llvm-15/include
  - -fparse-all-comments
  - -D__clang__