tmp_dir: gen_rfl
src_dir: ./
libs_dir: libs
include_dir: include
source_pattern: \.(cpp|c++|cc|cxx|h|hpp|hxx)$
cmake_pattern: ^.*/CMakeFiles/.+/CMake.+$
llvm_args:
  - --std=c++20
  - -I/usr/include/c++/14.2.0
  - -I/usr/include/c++/14.2.0/x86_64-alpine-linux-musl
  - -fparse-all-comments
  - -D__clang__